name: hello

on: push

jobs:
    job1:
        name: Test
        runs-on: windows-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4
            - name: Run the script
              run: python hello.py > out.txt
    job2:
        name: Build
        needs: job1
        runs-on: windows-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4
            - name: Download artifact
              uses: actions/upload-artifact@v4
              with:
                name: hello
                path: .
